provider:
  name: openfaas

functions:
  expressjs:
    lang: dockerfile
    handler: ./
    image: alexellis2/service:0.4.1
    annotations:
      com.openfaas.health.http.path: "/health"
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi

# faas-cli publish  --platforms linux/amd64,linux/arm64,linux/arm/7