apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
    {{- include "expressjs.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    {{- include "expressjs.selectorLabels" . | nindent 4 }}
  sessionAffinity: None